baseURL = ""
languageCode = "en"
title = "Zhaohua Blog"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "zhao hua"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "zhaohua Blog "
  subtitle = "~ Keep It Simple & Stupid ~"
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10

  # Choose your social networks
  email = "zhaohuap@gmail.com"
  github = "enhay"


  # Changyan Comments (China Only)
  changyan = false
  
  baiduTongji = "484edc35ca71228aa8ceb711a55d09e5"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
