baseURL = ""
languageCode = "en"
title = "Zhaohua Blog"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Copyright of your post
copyright = "©"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "zhao hua"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "zhaohua Blog "
  subtitle = "~ enjoy and have fun ~"
  description = "Hugo makes building websites fun again."
  paginate = 20

  # Choose your social networks
  email = "zhaohuap@gmail.com"
  github = "enhay"


  # Changyan Comments (China Only)
  changyan = false
  
  baiduTongji = "484edc35ca71228aa8ceb711a55d09e5"

  # ICP Number (China Only)
  ICP = "京ICP备18036514号-1"
